App\Entity\Book:
    attributes:
        id:
            groups: ['book']
        title:
            groups: ['book']
        image:
            groups: ['book']
        categories:
            groups: ['book']
        authors:
            groups: ['book']
        description:
            groups: ['book']
        score:
            groups: ['book']
        readAtAsString:
            groups: ['book']
            serialized_name: readAt
        createdAt:
            groups: ['book']


