services:
    db:
        image: mysql:8.0.20
        container_name: database
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_librarify2:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony_app
    php:
        container_name: app
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/librarify:cached
            - symfony_app_var:/var/www/librarify/var
            - symfony_app_vendor:/var/www/librarify/vendor
        networks:
            - symfony_app
    nginx:
        container_name: server
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/librarify:cached
            - symfony_app_var:/var/www/librarify/var
            - symfony_app_vendor:/var/www/librarify/vendor
        ports:
            - 80:80
        networks:
            - symfony_app
        env_file:
            - .env.nginx.local

volumes:
    symfony_app_var:
    symfony_app_vendor:
    db_librarify2:

networks:
    symfony_app: